version: '3'
services:
  middleware:
    build: ./middleware
    # env_file:
    #   - ./mysql/resources/mysql.env
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - ./data:/app/data
  
  frontend:
    build: ./frontend
    depends_on:
      - proxy
    ports:
      - "127.0.0.1:8889:8889"

  router:
    build: ./router
    depends_on:
      - proxy
      - frontend
    ports:
      - "127.0.0.1:80:80"
