services:
  
  backend:
    build: ./backend
    image: riesgoscached/backend
    ports:
      - 8000:8000
    volumes:
      - logs:/backend/data/logs
      - store:/backend/data/store
    environment:
      port: 8000
      maxStoreLifeTimeMinutes: 120
      sendMailTo: michael.langbein@dlr.de
      sourceEmail: test@test.com
      EqCatalogUrl: https://rz-vm140.gfz-potsdam.de/wps/WebProcessingService
      EqSimUrl: https://rz-vm140.gfz-potsdam.de/wps/WebProcessingService
      FragilityUrl: https://rz-vm140.gfz-potsdam.de/wps/WebProcessingService
      ExposureUrl: https://rz-vm140.gfz-potsdam.de/wps/WebProcessingService
      DeusUrl: https://rz-vm140.gfz-potsdam.de/wps/WebProcessingService
      NeptunusUrl: https://rz-vm140.gfz-potsdam.de/wps/WebProcessingService
      VolcanusUrl: https://rz-vm140.gfz-potsdam.de/wps/WebProcessingService
      TsunamiUrl: https://riesgos.52north.org/wps
      SysrelUrl: https://riesgos.52north.org/javaps/service
      SysrelEcuadorUrl: https://riesgos.52north.org/javaps/service
      LaharUrl: https://riesgos.52north.org/geoserver/ows
      CacheServer: http://localhost:8003/geoserver/riesgos/wms

  compare-frontend:
    build: ./compare-frontend
    image: riesgoscached/compare-frontend
    depends_on:
      - backend
    ports:
      - 8002:80
    environment:
      subPath: "/"
      backendUrl: http://localhost:8000
      allowedScenarios: '["ChileCached", "PeruCached"]'

  cache-server:
    image: docker.osgeo.org/geoserver:2.23.1
    ports:
      - 8003:8080
    environment:
      CORS_ENABLED: true
      SKIP_DEMO_DATA: true

      


volumes:
  logs: 
  store:

