version: '3'
services:
  middleware:
    build: ./middleware
    ports:
      - "127.0.0.1:8002:8008"
    volumes:
      - ./data:/app/data
  
  frontend:
    build: ./frontend
    depends_on:
      - middleware
    ports:
      - "127.0.0.1:8001:80"

  router:
    build: ./router
    depends_on:
      - middleware
      - frontend
    ports:
      - "127.0.0.1:8000:80"
