services:
  
  backend:
    build: ./backend
    ports:
      - ${backendPort}:${backendPort}
    volumes:
      - logs:/backend/data/logs
      - store:/backend/data/store
    environment:
      port: ${backendPort}
      maxStoreLifeTimeMinutes: ${maxStoreLifeTimeMinutes}
      adminEmails: ${adminEmails}
      sourceEmail: ${sourceEmail}

  monitor:
    build: ./monitor
    depends_on:
      - backend
    environment:
      # This url is called inside of docker-network, so "http://backend" gets resolved to the actual IP
      backendUrl: "http://backend"
      backendPort: ${backendPort}
      adminEmails: ${adminEmails}
      sourceEmail: ${sourceEmail}
      testServiceEveryMinutes: ${testServiceEveryMinutes}
  
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 8000:80
    environment:
      subPath: ${frontendSubPath}
      backendUrl: ${backendUrl}
      backendPort: ${backendPort}

  compare-frontend:
    build: ./compare-frontend
    depends_on:
      - backend
    ports:
      - 8001:80
    environment:
      subPath: ${compareFrontendSubPath}
      backendUrl: ${backendUrl}
      backendPort: ${backendPort}


volumes:
  logs: 
  store:

