services:
  
  backend:
    build: ./backend
    image: dlrriesgos/backend
    ports:
      - ${backendPort}:${backendPort}
    volumes:
      - logs:/backend/data/logs
      - store:/backend/data/store
    environment:
      port: ${backendPort}
      maxStoreLifeTimeMinutes: ${maxStoreLifeTimeMinutes}
      sendMailTo: ${sendMailTo}
      sourceEmail: ${sourceEmail}
      EqCatalogUrl: ${EqCatalogUrl}
      EqSimUrl: ${EqSimUrl}
      FragilityUrl: ${FragilityUrl}
      ExposureUrl: ${ExposureUrl}
      DeusUrl: ${DeusUrl}
      NeptunusUrl: ${NeptunusUrl}
      VolcanusUrl: ${VolcanusUrl}
      TsunamiUrl: ${TsunamiUrl}
      SysrelUrl: ${SysrelUrl}
      SysrelEcuadorUrl: ${SysrelEcuadorUrl}
      LaharUrl: ${LaharUrl}
  
  frontend:
    build: ./frontend
    image: dlrriesgos/frontend
    depends_on:
      - backend
    ports:
      - 8000:80
    environment:
      subPath: ${frontendSubPath}
      backendUrl: ${backendUrl}
      backendPort: ${backendPort}

  compare-frontend:
    build: ./compare-frontend
    image: dlrriesgos/compare-frontend
    depends_on:
      - backend
    ports:
      - 8001:80
    environment:
      subPath: ${compareFrontendSubPath}
      backendUrl: ${backendUrl}
      backendPort: ${backendPort}
      allowedScenarios: '["ChileCached", "PeruCached"]'

  cache-server:
    image: docker.osgeo.org/geoserver:2.23.1
    ports:
      - 8004:8080
    environment:
      CORS_ENABLED: true
      SKIP_DEMO_DATA: true
      
  # monitor:
  #   build: ./monitor
  #   image: dlrriesgos/monitor
  #   depends_on:
  #     - backend
  #   environment:
  #     # This url is called inside of docker-network, so "http://backend" gets resolved to the actual IP
  #     backendUrl: "http://backend"
  #     backendPort: ${backendPort}
  #     sendMailTo: ${sendMailTo}
  #     sourceEmail: ${sourceEmail}
  #     testServiceEveryMinutes: ${testServiceEveryMinutes}

      


volumes:
  logs: 
  store:

