version: '3'
services:
  middleware:
    build: ./middleware
    ports:
      - "8002:8008"
    volumes:
      - ./data:/app/data
  
  frontend:
    build: 
      context: ./frontend
      args:
        LOCAL_ARTIFACTS: "FALSE"  # set true to re-use local versions of node_modules and dist (if already present)
    depends_on:
      - middleware
    ports:
      - "8001:80"

  router:
    build: ./router
    depends_on:
      - middleware
      - frontend
    ports:
      - "8000:80"
