services:
  
  backend:
    build: ./backend
    ports:
      - ${backendPort}:${backendPort}
    volumes:
      - logs:data/logs
      - store:data/store
    environment:
      port: ${backendPort}
      maxStoreLifeTimeMinutes: ${maxStoreLifeTimeMinutes}
      adminEmails: ${adminEmails}
      sourceEmail: ${sourceEmail}

  monitor:
    build: ./monitor
    depends_on:
      - backend
    environment:
      backendUrl: ${backendUrl}
      backendPort: ${backendPort}
      adminEmails: ${adminEmail}
      sourceEmail: ${sourceEmail}
      testServiceEveryMinutes: ${testServiceEveryMinutes}
  
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 8000:80
    args:
      subPath: ${frontendSubPath}
      backendUrl: ${backendUrl}
      backendPort: ${backendPort}

  compare-frontend:
    build: ./compare-frontend
    depends_on:
      - backend
    ports:
      - 8001:80
    args:
      subPath: ${compareFrontendSubPath}
      backendUrl: ${backendUrl}
      backendPort: ${backendPort}


volumes:
  logs: 
  store:

